export const SET_FORMS = 'SET_FORMS';
export const HAS_LOADED = 'HAS_LOADED';
export const SET_CONTROLS = 'SET_CONTROLS';
export const SET_SAVED = 'SET_SAVED';
export const FORM_SUCCESSFUL = 'FORM_SUCCESSFUL';
export const CONTROL_SUCCESSFUL = 'CONTROL_SUCCESSFUL';
