export const SET_ACTIVE_FORM = 'SET_ACTIVE_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const ADD_CONTROL = 'ADD_CONTROL';
export const UPDATE_FORM_CONTROL = 'UPDATE_FORM_CONTROL';
export const DELETE_FORM_CONTROL = 'DELETE_FORM_CONTROL';
export const ADD_OPTIONS_TO_FORM_CONTROL = 'ADD_OPTIONS_TO_FORM_CONTROL';
